### ISSUE TITLE
There is an error, how can I fixed this?

### ISSUE THREAD

**Issue by KenwoodID** [flowtyone/flowty-realtime-lcm-canvas#4]
<img width="579" alt="error" src="https://github.com/flowtyone/flowty-realtime-lcm-canvas/assets/11765732/441ea02a-5f72-48b2-8e57-98e4caaf9b18">

Thanks

**Comment by flowtyone** [comment]
Did you by any chance change the model? if so what model did you try to use?

**Comment by KenwoodID** [comment]
I did not change the model, using the default one. models--Lykon--dreamshaper-7

**Comment by Gauss-G** [comment]
met the same Error, and the detail tracking info is as below 
`inference starts
  0%|                                                                     | 0/3 [00:00<?, ?it/s]
inference took 2.0s
Traceback (most recent call last):
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/ui.py", line 33, in process_image
    return infer(
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/main.py", line 94, in infer
    return pipe(
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py", line 891, in __call__
    noise_pred = self.unet(
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 1142, in forward
    sample = upsample_block(
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/diffusers/models/unet_2d_blocks.py", line 2475, in forward
    hidden_states = upsampler(hidden_states, upsample_size, scale=scale)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/diffusers/models/resnet.py", line 187, in forward
    hidden_states = F.interpolate(hidden_states, scale_factor=2.0, mode="nearest")
  File "/Users/gagao7/SourceCode/github/flowty-realtime-lcm-canvas/env/lib/python3.9/site-packages/torch/nn/functional.py", line 3983, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: "upsample_nearest2d_channels_last" not implemented for 'Half'
`
